name: properties
on: [push, pull_request]
jobs:
  test:
    name: Test ${{ matrix.os }} go${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ["1.19.x", "1.18.x"] # code works with 1.3.x but we need 1.7.x for Benchmark.Run

    steps:
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run Tests
        run: go test ./...
